### ISSUE TITLE
Attribute Clean-Up

### ISSUE THREAD

**Issue by brg468** [SecKatie/ha-wyzeapi#373]
**Is your feature request related to a problem? Please describe.**

As discussed [here](https://github.com/JoshuaMulliken/ha-wyzeapi/issues/333#issuecomment-1096995651), there are several attributes that are returned that are potentially adding to the database unnecessarily. Looking to see if any of these are being used in automations, scripts, etc., and could potentially be removed. Some that I've found:

- `State` - Already shown by entity state
- `Available` - Same as above
- `Device Model` - Already shown in device info.
- `Battery Percentage` - Discussed in link above
- `MAC` - Not really needed but also not shown anywhere else
- `RSSI` -  I can see how its nice to know, but also probably updates frequently adding to the database.

Feel free to add any others or comment. To be clear, these are items found under `attributes` of each entity on the frontend or developer tools. These should all be things that are available somewhere else or not routinely used but we would like some feedback before removal.

**Comment by tggman** [comment]
In general, I'm in favor of anything that reduces the size of, and how often data is written to, the database.
I myself have used the MAC for debugging purposes but wouldn't mind taking the extra step of looking up the IP address in my router to get the MAC

**Comment by JoshuaMulliken** [comment]
Thanks for the feedback @tggman!

I will hold this task open for 2 weeks to collect additional feedback and then we can start implementing any required changes.

**Comment by brg468** [comment]
One thing I noticed after re-reading the warning that was posted in the link above, is that the attributes are only written to the database when the entity state changes. That changes my thinking on this a bit. 

I still think `Battery Percentage` should be either removed or broken out into its own sensor (is it already?), and the duplicated attributes should definitely be removed. But for things like lights, switches, siren, etc., these things (more than likely) aren't generating many state changes so the impact on the database should be minimal. Things like MAC are static so the impact should be minimal. The less attributes for each entity the better, but maybe not all entities are equally important in that regard. Again just food for thought.


Bold added for emphasis 
*Entities that generate a significant amount of **state** changes can quickly increase the size of the database when the **extra_state_attributes also change frequently**. Minimize the number of extra_state_attributes for these entities by removing non-critical attributes or creating additional sensor entities.

**Comment by yoinx** [comment]
As far as I can recall, anything with a battery has had the battery broken out into it's own entity. That occurred after I had added it to the device info, which only occurred because I couldn't figure out linking the entities for batteries when I started with this.

I 100% support removing those for the device info. However, I know at least one person wanted them to stay to make them easier to get from node red. But, honestly, there are likely other ways to get the info from the devices in node red.

**Comment by JoeSchubert** [comment]
Did we decide against implementing this? It looks like the battery% is still in the device info.

Or did it not generate much difference in the database?

**Comment by brg468** [comment]
I don’t think it would have much of an impact on the database, but I also don’t have any devices with batteries. I still think removing the redundant attributes like state, available and model would be a good call.

**Comment by tggman** [comment]
Sorry guys if this is off topic?, but I didn't know where to put this question so this seemed like as good a place as any ...

@brg468 and @JoshuaMulliken I'm going all-IN with LIFX bulbs and all-OUT with pretty much everything Wyze. I noticed HACS has special / specific remove instructions. Are there any special remove instructions for the wyzeapy and/or ha-wyzeapi integrations?

And guys THANK YOU for all your efforts. It's been fun.

**Comment by brg468** [comment]
I don’t think there’s anything special, just delete the integration then you can remove it from HACS as well.

**Comment by brg468** [comment]
Let me know if you think I should pursue this @SecKatie, I keep forgetting about it. I think we decided it’s not really necessary but at the same time why have all these redundant attributes…

**Comment by SecKatie** [comment]
Definitely up to you! I don't have a preference either way.
