### ISSUE TITLE
[Feature Request] Support for air purifier 

### ISSUE THREAD

**Issue by rjmcfadd** [SecKatie/ha-wyzeapi#377]
Hello, will you be adding support for the new Wyze air purifier? Thanks!

**Comment by Geczy** [comment]
Any response?

**Comment by JoshuaMulliken** [comment]
I  do not have one of their air purifiers (nor do I really want one), but I would be happy to merge a PR that implements it.

**Comment by alexmourer** [comment]
I would be interested in this feature as well.

**Comment by zvarnes** [comment]
I would also be interested in this.
