### ISSUE TITLE
Thermostat control from Home Assistant nonfunctional

### ISSUE THREAD

**Issue by whundahl** [SecKatie/ha-wyzeapi#437]
Controlling the Wyze thermostat through the home assistant thermostat card in the UI doesn't change the set heating temperature on the thermostat.

**Comment by whundahl** [comment]
![image](https://user-images.githubusercontent.com/31379657/208260014-fce677b5-5b0a-4d6c-a23c-27afc44fba0c.png)

**Comment by whundahl** [comment]
Interestingly a different error is thrown for the set HVAC low temp. See below: 
![image](https://user-images.githubusercontent.com/31379657/208325623-88f6f1bf-0b54-4043-9963-490125bfda7f.png)

**Comment by stphnduvall** [comment]
I am having the same issue, I think it may be an issue with the thermostat itself or an issue with Wyze's API support. When I change the temperature setting in HA, the Wyze app reflects the changes while my thermostat does not. However when I change the mode (Auto/Heat/Cool/Off), both the app and the thermostat reflects the changes.

**Comment by IceDraken** [comment]
Been having this same issue.  All my automatons that change the temperature swing based on geolocation aren't working.   Was just wondering if and how I could help get this resolved.

**Comment by th3jesta** [comment]
Running into this same issue.

**Comment by SecKatie** [comment]
Does anyone have debug logs of when the call fails?

**Comment by SecKatie** [comment]
> aiodns.error.DNSError: (12, 'Timeout while contacting DNS servers')

So this error means it's a problem with your network configuration. I cannot fix DNS errors.

**Comment by stphnduvall** [comment]
I use cloudflare dns servers. I'll try switching when I get home and let
you know what happens.

**Comment by stphnduvall** [comment]
I removed my custom DNS configuration and retested the problem. There is no error in the logs and the issue persists. The thermostat currently reads 74deg and is set to 68deg. The Wzye app reflects the set point but the system is still in the 'idle' state.

One thing I will note is that when changing the current setting to a preset; Home, Away, Sleep, the air conditioning functions as expected.

This is what leads me to believe it is an issue with either the HA API not calling a function properly, or the Wyze API not functioning as expected.
