### ISSUE TITLE
Wyze Garage Cam v3 and Trigger Garage door opener via Home Assistant

### ISSUE THREAD

**Issue by Hawkins00000** [SecKatie/ha-wyzeapi#439]
I am trying to expose the Garage Door opener entities and after adding this integration, I still do not see the Garage Door Opener Button . I have the Wyze V3 Garage door cam with the added Garage Door Opener addon. Please advise. adn Thanks in advance.

**Comment by LordNex** [comment]
Found [This that might do it](https://github.com/mrlt8/docker-wyze-bridge)

**Comment by Hawkins00000** [comment]
Hi Josh,

Can you please be more specific?


  *   Should I upgrade?
  *   What should I expect?
  *   Does the update expose a new entity, for a long push to activate the garage door opener?

Thanks and Regards,
Chris Hawkins
(716) 566-0000 c

**Comment by cameronr** [comment]
@Hawkins00000 Did you ever figure this out?

**Comment by Hawkins00000** [comment]
NOPE!

Thanks and Regards,
Chris Hawkins
716-566-0000 c
________________________________

**Comment by dnestico** [comment]
I hope this is figured out, recently bought the garage door opener thinking it was possible already, damn.
