### ISSUE TITLE
Cam motion-switch does not work from HA

### ISSUE THREAD

**Issue by Ace0510** [SecKatie/ha-wyzeapi#445]
**Describe the bug**
I have 10 Cams V2 and V3 - When I turn on the motion switch in any camera it goes on for about 20' to 30' then it reverts to off.  If the motion is already on in the app it will not turn it off from HA.  If I turn the motion on/off in any Indvidual camera in Wyze app it will show in HA after refreshing the app or after 20' to 30'.  However, if from the Wyze app I turn a motion on in a group, it will not update HA until accessing the Event Recording screen in each camera. 

**To Reproduce**

1. Go to 'switch.xxcam_motion_detection'
2. Click on '.ON.'

**Expected behavior**
When I turn on the motion switch in any camera it goes on for about 20' to 30' then it reverts to off. 

**System configuration**
Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Frontend 20221213.1 - latest

**home-assistant.log**

```
<PUT YOUR LOG HERE>
```

**Comment by brg468** [comment]
Well that’s interesting, I just tried and had the same result. It was working a few weeks ago, I wonder if Wyze changed something…

**Comment by Ace0510** [comment]
And I was looking forward to finally control the motion within HA…   I hope you can figure out what is going on. Thank you for all your efforts!Alberto A CorreaOn Jan 9, 2023, at 4:09 PM, Brian Rogers ***@***.***> wrote:﻿
Well that’s interesting, I just tried and had the same result. It was working a few weeks ago, I wonder if Wyze changed something…

**Comment by brg468** [comment]
@Ace0510 are you up for a little testing? If so, I think I can walk you through running the changes

Download my branch from [here ](https://github.com/brg468/ha-wyzeapi/tree/update-motion-detection-switch). Place the `wyzeapi `folder in your `custom_components `folder, overwriting the one that's currently there.

Then download the upstream from [here.](https://github.com/brg468/wyzeapy/tree/update-motion-detection-switch) Place the wyzeapy folder directly in your config folder (there wont be one there currently). After that's all done restart HA.

It seems to be working on my V2 an V3 cameras as expected, with the one exception being turning a V2 camera's motion on or off from a group shortcut in the app doesn't seem to update the state in HA until you open that camera's Event Recording tab for some reason. The other issues you noted before seem to be fixed, but see if it works for you. Let me know if you have questions.

**Comment by Ace0510** [comment]
Hi Brian,Sure, I’ll do that tomorrow.  AlbertoOn Jan 12, 2023, at 5:32 PM, Brian Rogers ***@***.***> wrote:﻿
@Ace0510 are you up for a little testing? If so, I think I can walk you through running the changes
Download my branch from here . Place the wyzeapi folder in your custom_components folder, overwriting the one that's currently there.
Then download the upstream from here. Place the wyzeapy folder directly in your config folder (there wont be one there currently). After that's all done restart HA.
It seems to be working on my V2 an V3 cameras as expected, with the one exception being turning a V2 camera's motion on or off from a group shortcut in the app doesn't seem to update the state in HA until you open that camera's Event Recording tab for some reason. The other issues you noted before seem to be fixed, but see if it works for you. Let me know if you have questions.

**Comment by Ace0510** [comment]
Hi Brian,

This is what I have found out:

   - V3
      - I can turn on/off motion from HA. It works fine and anyone can use
      it this way.
      - From the app I can turn Motion ON and it updates HA after a
      few seconds.
      - From the app turning motion OFF  it updates HA after a while.
   -
   - V2
   - I can turn on/off motion from HA. It works fine and anyone can use it
      this way.
      - From the app I can turn Motion ON/OFF and it shows in HA after a
      while.
   - Group Motion
      - From HA  or the app  I can turn on/off  motion on all the cameras.
      However it will not update HA unless each camera Event Recording
screen is
      accessed from the app. So it makes it difficult to know the status.

Let me know if you have any other questions or if there is anything else I
can do.

Thank you very much for your help!

Alberto

**Comment by brg468** [comment]
@Ace0510 thanks for testing. I’m going to see if there’s a better way to pull status before I submit this, feel free to keep using it for now.

**Comment by WoosterInitiative** [comment]
@brg468 Is there a reason you haven't tried to PR this? This is also affecting my cameras. I've never tried to change these switches before, but I've got an automation I'd like to run and this would be great! I'd love to not have to hack around the HACS stuff any more than I have to.

Looks like a simple change, too. Does it break anything else?

**Comment by brg468** [comment]
@WoosterInitiative honestly, I forgot. The motion switches have been super unreliable and I was gonna try and mess around with it but never got around to it.  Did you try running my branches above and is it working for you?

**Comment by brg468** [comment]
Commenting to keep this open. This is still an issue I think.

**Comment by rocnydad** [comment]
Hey all - I was one of the original requestors for adding the ability to enable or disable motion sensing - thanks for bringing this in.

I am having an issue where when I use a scene or HA to turn off motion sensing for my outdoor v2 cam, after about 15 second the switch reverts back to an ON status.  Anyone else experiencing this?  I have not downloaded the branch mentioned above.  Not sure if this was the same issue.  Thx!
