### ISSUE TITLE
[Bug] Notifications, Motion Detection and Sirens Unavailable

### ISSUE THREAD

**Issue by hitnrun30** [SecKatie/ha-wyzeapi#453]
**Describe the bug**
All Notifications for devices, Motion Detection and Sirens are unavailable

**To Reproduce**
Added Integration and all are bad.

**Expected behavior**
Either not there or able to be deleted if they are not right.

**System configuration**
System: HA Supervisor
HA Version: 2023.1.7
WyzeApi Version: 0.1.17

![image](https://user-images.githubusercontent.com/23220612/214682854-4bd7b76b-e29b-4442-8c69-6ccfce48204c.png)

**Comment by jrDev1** [comment]
Is this going to be fixed? I’m trying to trigger automations when motion is detected…

**Comment by brg468** [comment]
> Is this going to be fixed? I’m trying to trigger automations when motion is detected…

There is not currently a good way to use camera motion detection as triggers.  They do report events but only when polled, which is only every 30 seconds or more. This is an API limitation.

**Comment by aaronsmith1234** [comment]
Hey @JoshuaMulliken, thanks for the great work here. I’m not sure if this is a separate issue or the same here, but when I add this integration via HACS, I can see and control my siren on my cam v3. However, I am not able to use them in any automation (e.g. if back door sensor left open for more than x seconds, trigger the alarm.) I’m unsure if this is an issue with HA or the integration.

Currently on 0.1.19 of the Wyze integration, HA 2023.6.1 via docker.
