### ISSUE TITLE
[Bug] Missing battery levels

### ISSUE THREAD

**Issue by magikid** [SecKatie/ha-wyzeapi#454]
**Describe the bug**
I have a Wyze Cam Outdoor V2 and a Wyze Video Doorbell Pro and neither of them report their battery status in Home Assistant.

![image](https://user-images.githubusercontent.com/115515/215163125-94b49a57-a14e-4f0d-966c-8b04e7e8ae26.png)

In looking over the logs, I see that both report their "electricity" which seems to be their battery level.

**Expected behavior**
I would expect the two devices to report their battery levels (so I can be alerted by HA when they're running low)

**System configuration**
System: Docker
HA Version:  2023.1.7
WyzeApi Version: 0.1.17

**home-assistant.log**

[home-assistant_2023-01-27T18-23-15.793Z-onlywyze.log](https://github.com/JoshuaMulliken/ha-wyzeapi/files/10522067/home-assistant_2023-01-27T18-23-15.793Z-onlywyze.log)

**Comment by Lord0fBytes** [comment]
I dont know if it is coincidence or not, but I am having the same issue where of the 4 outdoor cameras I have only the two I have CamPlus enabled on report the battery levels in HA.

**Comment by JoeSchubert** [comment]
> I dont know if it is coincidence or not, but I am having the same issue where of the 4 outdoor cameras I have only the two I have CamPlus enabled on report the battery levels in HA.

I'm not sure. I have at least the free version of camplus enabled on all of my camera since Wyze feature locked things behind it. I'm not really sure what gets stripped out of the response if you don't have it enabled, but it's entirely possible that they don't provide the information without it.

**Comment by jrDev1** [comment]
Would this be the case for using motion detection too? I don’t have cam plus.
