### ISSUE TITLE
[Feature Request] Wyze Sense Hub / Sensors

### ISSUE THREAD

**Issue by aad4321** [SecKatie/ha-wyzeapi#474]
I have the current generation Wyze sense Hub, some motion and door sensors. Is integration possible?

**Comment by jimcj1301** [comment]
This was once a feature in one of the Wyze HA Integrations. If I remember correctly it was removed because the binary sensors were beating up Wyze servers with the number of calls I think. I'd also like this back if there was a way. I'm no expert but doubtful it would be possible again.
