### ISSUE TITLE
Flood Light feature flipped between V3 and V3 Pro

### ISSUE THREAD

**Issue by uberoptix** [SecKatie/ha-wyzeapi#475]
**Describe the bug**
The V3 Poo offers a flood light, however the sensor for that feature is only available for V3 (non-Pro) cameras. Incorrect in both cases.

**To Reproduce**

**Expected behavior**

**System configuration**
System: 
HA Version: 
WyzeApi Version: 

**home-assistant.log**

```
<PUT YOUR LOG HERE>
```

**Comment by brg468** [comment]
The V3 does have the floodlight as an option, that's why it has the control for it. The pro can probably be added if you supply the device model number.

**Comment by KuhlBrandon** [comment]
Hate to bump a stale thread but I ran into this issue trying to set up some automations. My cam V3 pro does not have a floodlight entity but my regular cam v3's do. Pro model is HL_CAM3P
