### ISSUE TITLE
[Feature Request] Trigger Shortcuts from HA

### ISSUE THREAD

**Issue by Abba-** [SecKatie/ha-wyzeapi#477]
**Is your feature request related to a problem? Please describe.**
With the motion detection being a problem (#476) and in future stuff happening to break, it could be really useful to have a way to trigger shortcuts, since in the app we can always edit the shortcuts.

**Describe the solution you'd like**
A 'button' in HA that activates a shortcut from the Wyze app.

<3

**Comment by JoeSchubert** [comment]
I don't really know that this is something that would be provided by this integration. It sounds more like you're requesting some sort of macro from the Home Assistant app (on whichever platform you're using) that would then launch the Wyze app and click some shortcut. As far as I know, and I am only familiar with Android, the Wyze app does not expose their shortcuts to be launched via intents or anything. 

Are you able to provide any information that might facilitate this, or correct the information I provided above?

**Comment by Abba-** [comment]
My vague understanding of this integration in general is it's reversed the API calls the app makes?
So I was simply hoping it's possibly to trigger the Wyze app shortcuts also via API.

But considering that this doesn't show in Alexa then yea it might not be making an API call and it would be beyond on the scope of this...
