### ISSUE TITLE
[Bug] scene.create redux

### ISSUE THREAD

**Issue by brainhig** [SecKatie/ha-wyzeapi#480]
**Describe the bug**
When using scene.create with Wyze Bulb Color, if the bulb is in color mode when using scene.create, and then changing the bulb to a different color, then restoring the scene, it works as expected. If, however, the mode of the bulb is "White" when using scene.create, when the scene is restored, the bulb remains in color mode and the color temperature and "White" mode is not restored.

This behavior has been consistent for the last 6 months or so, through a couple of updates of wyzeapi.

**To Reproduce**
Set the Wyze Bulb Color to "White" mode and choose a color temperature (manually or programatically).

create a scene with the current state of the bulb
  - service: scene.create
    data:
      scene_id: office_state
      snapshot_entities:
        - light.office_inside

Set the Wyze Color Bulb to color mode and change color
        - service: light.turn_on
          data:
            rgb_color:
              - 255
              - 0
              - 0
            brightness_pct: 100
          target:
            device_id:
              - a231cdce0bba5a9da1b65e1ac1656b70

Restore saved scene
  - service: scene.turn_on
    target:
      entity_id: scene.office_state

**Expected behavior**
Scene should be restored to "White" mode and previous temperature

**System configuration**
System: Raspberry Pi HASS
HA Version: 2023.5.1
WyzeApi Version: 0.1.19
Local control of bulbs enabled

**Comment by brg468** [comment]
I had a chance to take a look at this, and I think its because the light component doesn't currently implement the color_mode property. Adding that seems to have fixed it for me. I'll get a PR together soon.

**Comment by brainhig** [comment]
Thank you, Brian. I made those changes to light.py and it's working perfectly :)

**Comment by brg468** [comment]
Glad it’s working for you. 

The trailing comma isn’t required but I think it’s added by Black (formatter) automatically when items are on separate lines. Doesn’t hurt either way.

**Comment by SecKatie** [comment]
New release has been made with the fix from #482 so I am closing this issue.
