### ISSUE TITLE
notifications on/off not working

### ISSUE THREAD

**Issue by sceccola** [SecKatie/ha-wyzeapi#483]
I just loaded this , and went to one of my cameras and turned off notifications....
Then I went to the Wyze App and it was still on, did I set up incorrectly?
The power on/off is not working as well.

Thanks
Sam

**Comment by brg468** [comment]
What model cameras? Did you refresh the app after toggling switches and did the switch state stay correct in HA? It doesn’t seem to update without refreshing.
