### ISSUE TITLE
[Feature Request] Add switch to enable/disable "Track Motion" on Wyze Cam Pan v3

### ISSUE THREAD

**Issue by janssjay** [SecKatie/ha-wyzeapi#484]
The Wyze Cam Pan v3 motion tracking tends to get confused during periods of high wind speeds.  Movement of the camera caused by high winds is confused as motion, which causes the camera to stop panning and get stuck on an object that isn't actually moving.
I'd like to create an automation to turn off "Track Motion" when my average wind speed exceeds a trigger speed, and then turn it back on when the winds subside.

**Comment by Rijswijker** [comment]
+1 I was just on GitHub to create a Feature Request :-)

**Comment by janssjay** [comment]
Commenting to renew this request and remove the Stale label.   Would really appreciate the feature.

**Comment by brg468** [comment]
I looked at it briefly and didn't see any way to accomplish this. I’ll check again when I have some time.

**Comment by brg468** [comment]
I looked again, and I don't see anything that indicates motion tracking in the API. At this point I would have to say this is not possible.
