### ISSUE TITLE
Wyze Changing API

### ISSUE THREAD

**Issue by Danrarbc** [SecKatie/ha-wyzeapi#485]
Just received an email from Wyze that they're require a new app version soon. Inside the email there's a note for people using home automation software about a portal for generating API keys going forward.

https://support.wyze.com/hc/en-us/articles/16129834216731?lid=87ac6t8mqos0

**Comment by MrM-code** [comment]
Wyze has a new security in place to block bots and automation scripts so it is better to use the new API endpoint that they provided in the email.

**Comment by zackoch** [comment]
oof. These wyze people never fail to amaze me. The must be implementing cert pinning or something on the 7th? Neat, that will be trivial to patch out lol.

It gets even better - the link which provides instructions to generate a key provides no documentation other than auth flow, unless I'm blind 😔

Oh, and triple md5 😆 what the actual heck.

**Comment by xdreamwalker** [comment]
I'm wondering if I'm going to need to prepare myself for a workaround using ifttt and Google Home to keep the other members of the house from trying to murder me once this integration breaks. 🙃

**Comment by brg468** [comment]
@JoshuaMulliken @JoeSchubert you guys still around?

**Comment by IxsharpxI** [comment]
would this API access make this (or other) intergrations work more easily? can we integrate this new API access?

**Comment by SecKatie** [comment]
I am still around. Keeping up with these guys has been difficult, and I have gotten very little communication. This may make things easier, but no comprehensive API documentation exists.

**Comment by TrickShow** [comment]
Do we have any further information on this. Currently, wyze integration is just broken and I can no longer log in with username and password.

**Comment by xdreamwalker** [comment]
Right now the integration is still working for me. However, I have not signed out. I was using it for locks and turning notifications on and off for a few cameras. I've just replaced the locks with some Yale units and if the integration stops working I'm going to have to patch something together with Google Home and IFTTT.
