### ISSUE TITLE
[Feature Request] Add Floodlight control for new Floodlight Pro

### ISSUE THREAD

**Issue by rykermorgan** [SecKatie/ha-wyzeapi#491]
**Describe the solution you'd like**
Controls for the new Floodlight Pro (LD_CFP) currently only include:
- Motion Detection
- Notifications
- Power
- Siren

I'd love to be able control the floodlight from HA, instead of having to do it from the Waze app. Then I could tie the light to a wireless button/switch.

**Describe alternatives you've considered**
Not sure there are any

**Additional context**
![image](https://github.com/SecKatie/ha-wyzeapi/assets/15041304/1bc3fa91-471e-430a-b70c-11448517503a)

**Comment by talormanda** [comment]
+1 - I need this in my life.

**Comment by talormanda** [comment]
Bump

**Comment by brg468** [comment]
Somebody wanna try some copy/paste editing? 

Change line 69 in `light.py` to this and restart. I don’t have this cam so I don’t know if that’s all it will take. 

`if camera.product_model in ["WYZE_CAKP2JFUS", "WYZEC3P"]: `

**Comment by brg468** [comment]
Ok, that’s probably not the right model number..what does HA show under device info for that cam?

**Comment by brg468** [comment]
Try 

`if camera.product_model in ["WYZE_CAKP2JFUS", "LD_CFP"]: `

**Comment by bryceandress** [comment]
That also did not work. I also tried `LDCFP`, `WYZE_LDCFP`, and `WYZE_LD_CFP`.

Just to confirm, reloading the integration is all that is needed? Or do I need to restart HA entirely?

**Comment by brg468** [comment]
I would try a full restart, reload sometimes throws an error. 

At a minimum I would think a switch would show up if the model number is correct, it may or may not work.

**Comment by bryceandress** [comment]
> Try
> 
> `if camera.product_model in ["WYZE_CAKP2JFUS", "LD_CFP"]: `

Alright with this suggestion and a full HA restart the switch for the Floodlight now appears. However, when turned on, it does not activate the lights and the switch will turn itself back off after a few seconds, presumably due to an error. I need to step away but can help troubleshoot further this weekend if needed.

**Comment by brg468** [comment]
Ok that’s not that unexpected, I’m sure it’s using a different property for the light. Hoping for the easy fix.

**Comment by brg468** [comment]
If somebody wants to share their device with me I can take a look at what it might take to get this working, assuming it’s similar to how the other floodlights work.

**Comment by talormanda** [comment]
> If somebody wants to share their device with me I can take a look at what it might take to get this working, assuming it’s similar to how the other floodlights work.

Were you able to get this working? If not, I can try to share my device for a limited time to see if you can spot this to get it working.

**Comment by brg468** [comment]
I have not had anybody share with me, but if you’d like to share to brg468@hotmail.com I can take a look when I have some time.

**Comment by talormanda** [comment]
> I have not had anybody share with me, but if you’d like to share to [brg468@hotmail.com](mailto:brg468@hotmail.com) I can take a look when I have some time.

I will send you an email to get a more precise communication. I can't share it for an indefinite amount of time so you will have to let me know.
