### ISSUE TITLE
[Bug] WyzeAPI fails to load in 2023.8.0

### ISSUE THREAD

**Issue by ejpenney** [SecKatie/ha-wyzeapi#501]
**Describe the bug**

**To Reproduce**

1. Go to Settings
2. Click on Update to 2023.8.0 Core
3. Restart
4. Sensors aren't loaded
5. Error below in logs

**Expected behavior**

**System configuration**
System: HAOS (VM)
HA Version: 2023.8.0
WyzeApi Version: 0.1.20

**home-assistant.log**

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:619
Integration: Sensor (documentation, issues)
First occurred: 7:44:03 PM (8 occurrences)
Last logged: 9:33:44 PM

Error adding entities for domain sensor with platform wyzeapi
Error while setting up wyzeapi platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'type'

```

**Comment by brg468** [comment]
It’s probably these 2 lines. Looks like `type` is no longer a valid key for device info. I’ll be able to get a PR in tomorrow probably. Or if you have time trying removing those lines. I don’t have these sensors so I can’t know for sure. 

https://github.com/SecKatie/ha-wyzeapi/blob/c48a91f3aaa69e1a345d4d35a0369c25a8bd09b8/custom_components/wyzeapi/sensor.py#L138

https://github.com/SecKatie/ha-wyzeapi/blob/c48a91f3aaa69e1a345d4d35a0369c25a8bd09b8/custom_components/wyzeapi/sensor.py#L205

**Comment by ejpenney** [comment]
Just commented out those two lines and restarted, looks like that did the trick!

**Comment by Dee76** [comment]
Worked here as well. 👍

**Comment by brg468** [comment]
Thanks for testing guys. PR submitted.
