### ISSUE TITLE
[Bug] Light Bulbs no attribute 'color_mode' error message

### ISSUE THREAD

**Issue by cohenavi** [SecKatie/ha-wyzeapi#510]
Ever since updating to HA 2023.8.0 and wyze 0.1.22 I get the following error message when attempting to control wyze bulb (original version 1 bulb):

Failed to call service light/turn_on. 'Bulb' object has no attribute 'color_mode'

**Comment by svenugop** [comment]
Running into the same issue.

**Comment by brg468** [comment]
See the comments in https://github.com/SecKatie/ha-wyzeapi/issues/506 for a fix. Waiting on an updated version of the integration to be published.

**Comment by svenugop** [comment]
Nice! Will try this out

> See the comments in #504 for a fix. Waiting on an updated version of the integration to be published.

**Comment by svenugop** [comment]
@brg468 ... Making the change to light.py and restarting HA fixed it for me.
