### ISSUE TITLE
[Bug] Wyze Lock state changes from Lock to UnLock (or vice-versa) several times

### ISSUE THREAD

**Issue by GuillaumeB-GitHub** [SecKatie/ha-wyzeapi#511]
Wyze Lock state changes from Lock to UnLock (or vice-versa) several times.

Just click Lock or UnLock in HA and look at the state of the lock: it will switch several times. See screenshot attached.
The state should go to Locking/UnLocking and then Locked/UnLocked

There is a bug in the code in lock.py in the functions async_lock and async_unlock : these functions should set the state to UnLocking or Locking not Locked/UnLocked.

**Comment by vapuri** [comment]
I'm seeing the same issue as described by @GuillaumeB-GitHub with my wyze lock.

**Comment by rgnet5** [comment]
I am also seeing this issue.  Can we reopen?
