### ISSUE TITLE
Suddenly drops off network and needs new api key

### ISSUE THREAD

**Issue by Pronown** [SecKatie/ha-wyzeapi#514]
**Describe the bug**

All devices become unresponsive, upon attempting to reload the integration, it fails and won't sign back in until I use a new api key
**To Reproduce**

1. Use Wyze Integration
2. Wait for it to stop working (5 mins to 4 days)
3. Try to control lights
4. No bueno

**Expected behavior**

Expect lights and switches to function, instead they do not
**System configuration**
System: 
Hass OS
HA Version:  
2023.8.4
WyzeApi Version: 

**home-assistant.log**

```
<PUT YOUR LOG HERE>
```

**Comment by brg468** [comment]
Duplicate of https://github.com/SecKatie/ha-wyzeapi/issues/509
