### ISSUE TITLE
[Feature Request] Support for Wyze Air Purifier

### ISSUE THREAD

**Issue by freddydopfel** [SecKatie/ha-wyzeapi#516]
**Describe the solution you'd like**
The ability to use the HA Wyze add-on to detect and control Air purifiers. Including:
On/OFF
Fan Speed
Nice to have:
Sleep Mode
PM 2.5 sensor
Fan mode (manual vs auto)

**Describe alternatives you've considered**
Unfortunately, Wyze does not integrate the air purifiers with IFTTT, so controlling them with HA through IFTTT doesn't work

**Additional context**
Thank you for the amazing work you have already done!

**Comment by cbarham84** [comment]
Would love to see this added as well
