### ISSUE TITLE
[Bug] Motion detection switches aren't working for doorbell

### ISSUE THREAD

**Issue by Abba-** [SecKatie/ha-wyzeapi#517]
**Describe the bug**
 Toggling the switch for 'Motion Detection' or 'Power' for a doorbell doesn't work.

**To Reproduce**

1. Turn off Doorbell Motion Detection from dashboard / entity
2. Wait 20-45 seconds (presumably the amount of time for it to poll)
3. Switch will return to on position.

**Expected behavior**

Motion: Motion is supported in the app (Settings -> event recording -> motion detection) so would expect this switch to show as off in the app (and the entity to reflect the off state).

Power: There isn't a power button on the app for doorbells, so this is probably simply unsupported.
Siren: Likewise, I dont think there is a siren option

**System configuration**
System: As Virtual Machine 10.5 on Unraid
HA Version:  2023.9.2
WyzeApi Version: 0.1.22

**Comment by Abba-** [comment]
Keeping this active….

**Comment by brg468** [comment]
I don’t think motion switches work on the doorbell, so really we should not add the motion switch. Can you post the model number from the device page in HA for the doorbell and I can add it to the list of cameras that don’t support motion switch.

**Comment by Abba-** [comment]
They absolutely do have a motion detection switch. They don’t have a regular power switch. They only capture motion.  (See first post)

HomeAssistant shows WYZEDB3 by WyzeLabs

**Comment by brg468** [comment]
I believe you that they have a motion switch, but apparently it doesn’t work the same as the other cameras. Without having one I can’t do much other than remove the switch if it isn’t working. If you or somebody wants to share the device I can see if it can be done but there’s no guarantee, some of the newer cams seem to use a different protocol for these things that isn’t supported through the API (floodlight pro is one of them)

**Comment by Abba-** [comment]
Happy to share it, do you have email where we can continue conversation?

**Comment by brg468** [comment]
email is brg468@hotmail.com, you can share to that if you'd like.

brg468 on discord also

**Comment by Abba-** [comment]
Communication ongoing…

**Comment by janssjay** [comment]
The switch does appear to toggle the "Motion Event Recordings" check-box in the Wyze app, but then the HA switch always resets to "On", even if the Wyze option is unchecked.

**Comment by Abba-** [comment]
Investigating....

**Comment by brg468** [comment]
I put in a small change to how motion switches are controlled. I'm not sure if it will have any effect on the doorbell or not.

https://github.com/SecKatie/wyzeapy/pull/82

**Comment by janssjay** [comment]
Have the same problem/experience with the Cam Pan v3 and Cam v3.  Motion detection toggle does not affect the app and always returns to ON regardless of the state in the app.

**Comment by brg468** [comment]
@janssjay are you running the latest version(0.1.24)? This should have been fixed in that release.

**Comment by janssjay** [comment]
@brg468 I just upgraded to 1.24 and retested.   Now the Motion Detection toggle stays where set, but it controls the "Motion Event Recordings" toggle, not the "Track Motion" toggle for the Cam Pan v3.  As for the Cam v3, the Motion Detection toggle also stays where set but unsuccessfully attempts to control the "Motion Tagging" option in the app.  One time it momentarily turned this option off but then reset with a "network unstable" error.  After that, it no longer had any impact.

**Comment by Abba-** [comment]
Communication ongoing

**Comment by SecKatie** [comment]
Its been merged @Abba- can you check now?

**Comment by Monacoslo** [comment]
Is there a way do enable back motion detection (sensor for automations) on regular Wyze cams?

**Comment by brg468** [comment]
@Monacoslo see this comment. 

https://github.com/SecKatie/ha-wyzeapi/issues/320#issuecomment-1001523837

**Comment by Abba-** [comment]
> Its been merged @Abba- can you check now?

Based on my testing with 0.1.27, 4 switches appear under the Device info for the WYZEDB3.
Also can I request you reopen #559 please as it directly relates to how errors below can be handled.

**Motion Detection:**
Seem to be unchanged from original report. 
The app allows motion detection toggle at Settings -> event recording -> motion detection.
However, the API now now throws an "unauthorized operation" rather then silently reverting.

**Notification**
✅This turned off notifications as expected.

**Power**
This throws an "unauthorized operation".  I agree there is no option for this and it should be removed for the doorbell.

**Siren**
This throws an "unauthorized operation".  I agree there is no option for this and it should be removed for the doorbell.

**Comment by Abba-** [comment]
unstale awaiting sharing details....

**Comment by Abba-** [comment]
@brg468 @SecKatie  can we unstale this please?

**Comment by brg468** [comment]
Looking at the notes of https://github.com/SecKatie/ha-wyzeapi/pull/607, the power switch was removed and the motion toggle was not able to be fixed.

**Comment by Abba-** [comment]
@KyGuy2002, based on #607 its impossible to fix the motion toggle?
(FWIW I have the non-pro Doorbell, although I doubt API is all that different).
