### ISSUE TITLE
Request ability to control garage door switch attached to Wyze Cam 3

### ISSUE THREAD

**Issue by jpetersheim** [SecKatie/ha-wyzeapi#520]
I'd love to see the ability to control the garage door opener. 
It comes packaged with a Wyze Cam V3 (Model: WYZE_CAKP2JFUS). This set up is very similar to the Wyze Floodlight attached to a WYZE_CAKP2JFUS.

Nuances:
There is a QR code on your garage door that signifies to the camera that the door is closed.
I found that the garage door command is just a trigger (https://github.com/mrlt8/docker-wyze-bridge/issues/997#issue-1897139928)
If it is closed (QR detected), the door opens. If it is open, the door closes.

Alternatives:
I've looked at Docker Wyze Bridge and they don't have this capability either (https://github.com/mrlt8/docker-wyze-bridge)

I am happy to share my device on a call if anyone wants to work on developing this.

![image](https://github.com/SecKatie/ha-wyzeapi/assets/42748029/545e6253-1937-4fce-a942-2df58acad30d)

**Comment by Lukejb14** [comment]
This issue may now be more critical.

With the MyQ integration discontinued, this may be super helpful for the millions of people with MyQ garage doors.

**Comment by mikealanni** [comment]
I'm planning to buy wyze garbage door, if this can be integrated in buying it tomorrow

**Comment by mikealanni** [comment]
Endpoint for garage status can be getting from
https://api.wyzecam.com/app/v2/device/get_property_list

It will return P1056, if 1 then garage open, 0 or 2 close. I think 0 when run by rule, 2 when run  of an endpoint 
https://api.wyzecam.com/app/v2/auto/run_action
With action 
"action_key": "garage_door_trigger"

I really would this be integrated as its a neat feature.

**Comment by delikat** [comment]
starting to look into this as I have a couple garage door accessories I'd love to work in HA.

[homebridge-wyze-smart-home](https://github.com/jfarmer08/homebridge-wyze-smart-home) seems to have a [working implementation](https://github.com/jfarmer08/homebridge-wyze-smart-home/blob/main/src/accessories/WyzeCamera.js#L162-L167), though they're looking at `P1301` for garage door state. triggering the opener is done by running the `garage_door_trigger` action as @mikealanni mentioned.

**Comment by mikealanni** [comment]
@delikat 

I have this setup in my home assistant and it's working with some automated geo tracking



`command_line:
  - sensor:
      name: "Garage Door Status"
      command: >
        curl -X POST -H "Content-Type: application/json" -d '{"sc": "xxx", "sv": "xxx", "app_ver": "com.hualai___2.47.0.373", "ts": 1702266071435, "access_token": "{{ state_attr('sensor.garage_door_token', 'data')['access_token'] | default('') }}", "phone_id": "xxx", "app_name": "com.hualai", "device_mac": "xxxx", "device_model": "WYZE_CAKP2JFUS", "target_pid_list": ["P1049", "P1050", "P1056"]}' https://api.wyzecam.com/app/v2/device/get_property_list
      scan_interval: 5
      json_attributes:
        - data
      value_template: >
        {% set data = value_json.data %}
        {% if data and data.property_list %}
        {% set garage_door_status = data.property_list | selectattr("pid", "eq", "P1056") | map(attribute="value") | first %}
        {% if garage_door_status == "1" %}
          Open
        {% elif garage_door_status == "2" or garage_door_status == "0" %}
          Closed
        {% else %}
         Unknown
        {% endif %}
        {% else %}
          Unknown
        {% endif %}
`

**Comment by delikat** [comment]
@mikealanni awesome, thanks for sharing! I'm a little confused since `P1056` is [also used for floodlight status](https://github.com/SecKatie/wyzeapy/blob/bb5323b3a394118bfd7e5fafeb9253984e987617/src/wyzeapy/types.py#L105). Maybe it just represents generic accessory on/off state? I'll poke around the API a bit.

**Comment by mikealanni** [comment]
I'm not expert but I was monitoring the app and saw that P1056 changed when door open and close so I use it 😅
