### ISSUE TITLE
[Bug] Wyze Outdoor Cam V2 Motion Dection State keeps reverting back to On

### ISSUE THREAD

**Issue by rocnydad** [SecKatie/ha-wyzeapi#526]
**Describe the bug**
I have a scene that set the Motion Detection setting to Off. When the scene fires, the state of motion detection is set to off for a few seconds and then reverts back to On

This also happens when I manually set the Motion Detection state to off from HA. After a few seconds it switches back to On

The Notifications setting does not behave this way

**Expected behavior**
When I set the state to off, it should remain off until another event changes the state.

HA Version: 2023.11.1
WyzeApi Version:

**Comment by slowfellow** [comment]
I am having the same problems, not sure how I can help to fix this.

**Comment by rovicomm** [comment]
I also have this issue.
