### ISSUE TITLE
[Feature Request] Be able to control Track Motion and Pan Scan

### ISSUE THREAD

**Issue by goug76** [SecKatie/ha-wyzeapi#529]
I would love the ability to control Track Motion and Pan Scan on my Pan Cam cameras.  When I am away from home, I turn these features on to monitor.  When I return home, I turn them off. Being able to do this in Home Assistant would be awesome.

Alternatively, the ability to fire off our rules from inside HA would also work.  We could do all our configurations in the Wyze app, and then in HA, we could trigger these rules.

**Comment by crystaliss** [comment]
+1 this would be great as I have the same use case.
