### ISSUE TITLE
 helpers/deprecation.py:205[Bug] <short description of issue>

### ISSUE THREAD

**Issue by Ace0510** [SecKatie/ha-wyzeapi#537]
**Describe the bug**
Logger: homeassistant.components.siren
Source: helpers/deprecation.py:205
Integration: Siren (documentation, issues)
First occurred: 11:37:07 AM (4 occurrences)
Last logged: 11:37:07 AM

SUPPORT_TURN_OFF was used from wyzeapi, this is a deprecated constant which will be removed in HA Core 2025.1. Use SirenEntityFeature.TURN_OFF instead, please create a bug report at https://github.com/SecKatie/ha-wyzeapi/issues
SUPPORT_TURN_ON was used from wyzeapi, this is a deprecated constant which will be removed in HA Core 2025.1. Use SirenEntityFeature.TURN_ON instead, please create a bug report at https://github.com/SecKatie/ha-wyzeapi/issues
SUPPORT_ALARM_ARM_HOME was used from wyzeapi, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_HOME instead, please create a bug report at https://github.com/SecKatie/ha-wyzeapi/issues
SUPPORT_ALARM_ARM_AWAY was used from wyzeapi, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/SecKatie/ha-wyzeapi/issues
TEMP_FAHRENHEIT was used from wyzeapi, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please create a bug report at https://github.com/SecKatie/ha-wyzeapi/issues
TEMP_CELSIUS was used from wyzeapi, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/SecKatie/ha-wyzeapi/issues
Logger: homeassistant.util.logging
Source: util/logging.py:102
First occurred: 11:37:18 AM (10 occurrences)
Last logged: 11:45:11 AM

Exception in handle_camera_update when dispatching 'wyzeapi.camera_updated-GW_GC2_D03F2777F7D7': (<Device: DeviceTypes.CAMERA, GW_GC2_D03F2777F7D7>,) Traceback (most recent call last): File "/config/custom_components/wyzeapi/switch.py", line 455, in handle_camera_update self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state state, attr, capabilities, shadowed_attr = self.__async_calculate_state() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in __async_calculate_state state = self._stringify_state(available) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 947, in _stringify_state if (state := self.state) is None: ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1553, in state if (is_on := self.is_on) is None: ^^^^^^^^^^ File "/config/custom_components/wyzeapi/switch.py", line 444, in is_on return self._device.motion ^^^^^^^^^^^^^^^^^^^ AttributeError: 'Camera' object has no attribute 'motion'
**To Reproduce**

1. Go to '..logs.'

**Expected behavior**

**System configuration**
Core
2024.1.2
Supervisor
2023.12.0
Operating System
11.3
Frontend
20240104.0
WyzeApi Version: 

**home-assistant.log**

```
<PUT YOUR LOG HERE>
```

**Comment by dualtronic** [comment]
These errors really fill the logs.  Hope it can be updated without too much trouble.
