### ISSUE TITLE
[Bug] Wyze thermostat API calls work - confirmed in app. Thermostat doesn't adjust, shows previous temp set

### ISSUE THREAD

**Issue by is33** [SecKatie/ha-wyzeapi#540]
**Describe the bug**
Wyze thermostat API calls work - confirmed in app. Thermostat doesn't adjust, shows previous temp set

**To Reproduce**

Change temp in HA

**Expected behavior**
Thermostat to adjust - again I am seeing it reflected in the app, the thermostat never changes. When changed in app, it works

**System configuration**
System: HA via Proxmox. However, same result on several other version deployed due to failures
```
HA Version: 
Core
2024.1.3
Supervisor
2023.12.1
Operating System
11.4
```

WyzeApi Version: 0.1.23

**home-assistant.log**
Nothing logged

**Comment by greymoment** [comment]
The thermostat works great, but always shows idle even when heating.
