### ISSUE TITLE
[Bug] Must reprovide cloud credentials and API after Assistant Core Patches installed

### ISSUE THREAD

**Issue by JosephRDawson** [SecKatie/ha-wyzeapi#542]
**Describe the bug**
After an update to the Assistant Core or patches to the Home Assistant core I must reconfigure the service by providing login information and API information. 
I am using a Home Assistant Greene box.

**To Reproduce**

1. Go to Setup service
2. Do a core upgrade or patch on home assistant
3. Reboot Home Assistant
4. Warning that the Wyse service is not configured anymore.

**Expected behavior**
I expect not to have to re-configure after updates to core.

**System configuration**
Home assistant Green hardware
 Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

**Comment by JosephRDawson** [comment]
What logs are you looking for?

The home assistant Google Drive backup logs look fine.
It is just after an update it forgets its configuration.

01-24 10:03:24 INFO Starting server on port 809901-24 10:03:24 INFO
Server started01-24 10:03:24 INFO Syncing Backups01-24 10:03:25 INFO
Uploading 'Full Backup 2024-01-22 00:00:00' to Google Drive01-24
10:04:08 INFO A backup directory file was modified, we'll check for
new backups soon.01-24 10:04:50 INFO Syncing Backups01-24 10:04:50
INFO Requesting a new backup01-24 10:04:56 INFO Syncing Backups01-24
10:05:16 INFO Backup finished01-24 10:05:16 INFO Syncing Backups01-24
10:05:17 INFO Uploading 'Full Backup 2024-01-24 10:04:50' to Google
Drive01-24 12:57:28 INFO Syncing Backups01-24 14:53:23 INFO Syncing
Backups01-24 17:02:14 INFO Syncing Backups01-24 19:33:17 INFO Syncing
Backups01-24 21:24:18 INFO Syncing Backups01-25 00:00:00 INFO Syncing
Backups01-25 00:00:00 INFO Requesting a new backup01-25 00:00:23 INFO
Backup finished01-25 00:00:23 INFO Syncing Backups01-25 00:00:24 INFO
Uploading 'Full Backup 2024-01-25 00:00:00' to Google Drive01-25
02:18:51 INFO Syncing Backups01-25 04:20:28 INFO Syncing Backups01-25
05:58:53 INFO Syncing Backups01-25 06:03:25 INFO A backup directory
file was modified, we'll check for new backups soon.01-25 08:47:06
INFO Syncing Backups01-25 11:00:05 INFO Syncing Backups01-25 13:38:04
INFO Syncing Backups01-25 15:16:59 INFO Syncing Backups01-25 16:54:43
INFO Syncing Backups01-25 19:17:11 INFO Syncing Backups01-25 20:57:37
INFO Syncing Backups01-25 23:36:26 INFO Syncing Backups01-26 00:00:00
INFO Syncing Backups01-26 00:00:00 INFO Requesting a new backup01-26
00:00:22 INFO Backup finished01-26 00:00:22 INFO Syncing Backups01-26
00:00:23 INFO Uploading 'Full Backup 2024-01-26 00:00:00' to Google
Drive01-26 01:31:22 INFO Syncing Backups01-26 02:03:26 INFO A backup
directory file was modified, we'll check for new backups soon.01-26
04:23:37 INFO Syncing Backups01-26 06:27:11 INFO Syncing Backups01-26
07:59:10 INFO Syncing Backups01-26 09:38:26 INFO Syncing Backups01-26
11:30:08 INFO Syncing Backups01-26 13:06:42 INFO Syncing Backups01-26
14:42:43 INFO Syncing Backups01-26 17:24:33 INFO Syncing Backups

**Comment by brg468** [comment]
Anything related to Wyze, but now I’m not sure this is a Wyze issue. Sounds like your setup is dumping config entries or something. Is this happening with other integrations?

**Comment by JosephRDawson** [comment]
Sorry I grabbed the wrong logs totally LOL.. Brain was off-line.
I will grab the right ones.

**Comment by JosephRDawson** [comment]
[home-assistant_2024-01-26T21-49-52.588Z.log](https://github.com/SecKatie/ha-wyzeapi/files/14069622/home-assistant_2024-01-26T21-49-52.588Z.log)

This should help.

**Comment by kvoth1** [comment]
Any update? Today after updating ha os Wyze stopped working for me.

**Comment by brg468** [comment]
Unfortunately I didn’t see anything in the logs that was helpful. @kvoth1 were your logs similar?
