### ISSUE TITLE
[Bug] Not getting any motion notices anymore.

### ISSUE THREAD

**Issue by JosephRDawson** [SecKatie/ha-wyzeapi#544]
Since the latest Wyze App and cloud updates I don't get any motion notfications in Home Assistant anymore.
The intergraion can turn off and on lights still but no motion notices on cameras with the latest firmware on Wyze V3, Wyze OG and Pan V2 camera.

**Comment by brg468** [comment]
How were you getting notifications from these devices before?

**Comment by JosephRDawson** [comment]
I thought the motion triggers went off like other motion triggers. Are you saying that they never worked?  My logs now never show activity from them. I assumed that they did work previously. But maybe they never did. And if they didn’t why are they variables? All the best,JoeOn Feb 6, 2024, at 3:57 PM, Brian Rogers ***@***.***> wrote:﻿
How were you getting notifications from these devices before?

**Comment by brg468** [comment]
Are you talking triggers in an automation? I don't think that is an option, at least not that I see. I know the binary sensors for motion have been disabled for a while now. If I'm off base here let me know.

**Comment by JosephRDawson** [comment]
Ok so what can you use them for I thought they would be triggers?
Are you saying the wize integration is just useful for plus and switches
and can't do motion triggers on cameras?

----------------------------------------------------------
http://bitstop.ca

**Comment by brg468** [comment]
The cameras cannot be used as motion sensors. I think that changed about 3 years ago because of rate limiting issues with Wyze. You can control power, notifications and motion detection on most of the cameras.
