### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by freespiritstays** [SecKatie/ha-wyzeapi#557]
**Describe the bug**
Error when updating in Home Assistant

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/base.py:529
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 6:34:24 PM (1 occurrences)
Last logged: 6:34:24 PM

[140612282725440] Error handling message: Unknown error (unknown_error) pedro from 172.20.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 516, in websocket_release_notes
    await entity.async_release_notes(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/update.py", line 140, in async_release_notes
    releases = await self.repository.get_releases(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/base.py", line 1041, in get_releases
    response = await self.hacs.async_github_api_method(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/base.py", line 529, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Timeout of 20 reached while waiting for https://api.github.com/repos/SecKatie/ha-wyzeapi/releases
```

**Comment by freespiritstays** [comment]
This issue broke my home assistant, now many other integrations stopped working
2024-03-19 18:52:07.722 ERROR (MainThread) [homeassistant.setup] Setup failed for 'wyzeapi': Integration not found.
2024-03-19 18:52:40.018 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: ring, alexa_media, tuya
2024-03-19 18:53:23.056 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Integration 'wyzeapi' not found.
2024-03-19 18:53:40.077 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: ring, alexa_media, tuya
2024-03-19 18:54:40.158 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: ring, alexa_media, tuya

**Comment by brg468** [comment]
Were you able to resolve this?

**Comment by shomanjk** [comment]
I believe I may be having the same issue.  When I upgraded Home Assistant core from 2024.3.0 to 2024.3.3 it seems to have broken the wyzeapi integration.  Perhaps these logs help?

**Comment by freespiritstays** [comment]
unfortunately not

Unable to install package wyzeapy==0.5.21: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x737443167950>: Failed to establish a new connection: [Errno -3] Try again')': /packages/46/b5/d617f992b0e582b7564f0011c1d55bc219e73d7863e2a1ffa54a11daa8c2/wyzeapy-0.5.21-py3-none-any.whl.metadata WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x737443167bc0>: Failed to establish a new connection: [Errno -3] Try again')': /packages/46/b5/d617f992b0e582b7564f0011c1d55bc219e73d7863e2a1ffa54a11daa8c2/wyzeapy-0.5.21-py3-none-any.whl.metadata WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x737443167ef0>: Failed to establish a new connection: [Errno -3] Try again')': /packages/46/b5/d617f992b0e582b7564f0011c1d55bc219e73d7863e2a1ffa54a11daa8c2/wyzeapy-0.5.21-py3-none-any.whl.metadata WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7374432debd0>: Failed to establish a new connection: [Errno -3] Try again')': /packages/46/b5/d617f992b0e582b7564f0011c1d55bc219e73d7863e2a1ffa54a11daa8c2/wyzeapy-0.5.21-py3-none-any.whl.metadata WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x737443014230>: Failed to establish a new connection: [Errno -3] Try again')': /packages/46/b5/d617f992b0e582b7564f0011c1d55bc219e73d7863e2a1ffa54a11daa8c2/wyzeapy-0.5.21-py3-none-any.whl.metadata ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/46/b5/d617f992b0e582b7564f0011c1d55bc219e73d7863e2a1ffa54a11daa8c2/wyzeapy-0.5.21-py3-none-any.whl.metadata (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x737443014440>: Failed to establish a new connection: [Errno -3] Try again'))
Unable to install package wyzeapy==0.5.21: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x732a6fc4ba10>: Failed to establish a new connection: [Errno -3] Try again')': /packages/46/b5/d617f992b0e582b7564f0011c1d55bc219e73d7863e2a1ffa54a11daa8c2/wyzeapy-0.5.21-py3-none-any.whl.metadata WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x732a6fd00860>: Failed to establish a new connection: [Errno -3] Try again')': /packages/46/b5/d617f992b0e582b7564f0011c1d55bc219e73d7863e2a1ffa54a11daa8c2/wyzeapy-0.5.21-py3-none-any.whl.metadata WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x732a6fb04200>: Failed to establish a new connection: [Errno -3] Try again')': /packages/46/b5/d617f992b0e582b7564f0011c1d55bc219e73d7863e2a1ffa54a11daa8c2/wyzeapy-0.5.21-py3-none-any.whl.metadata WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x732a6fb04410>: Failed to establish a new connection: [Errno -3] Try again')': /packages/46/b5/d617f992b0e582b7564f0011c1d55bc219e73d7863e2a1ffa54a11daa8c2/wyzeapy-0.5.21-py3-none-any.whl.metadata WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x732a6fb04620>: Failed to establish a new connection: [Errno -3] Try again')': /packages/46/b5/d617f992b0e582b7564f0011c1d55bc219e73d7863e2a1ffa54a11daa8c2/wyzeapy-0.5.21-py3-none-any.whl.metadata ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/46/b5/d617f992b0e582b7564f0011c1d55bc219e73d7863e2a1ffa54a11daa8c2/wyzeapy-0.5.21-py3-none-any.whl.metadata (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x732a6fb04890>: Failed to establish a new connection: [Errno -3] Try again'))
