### ISSUE TITLE
Notification toggle no longer working

### ISSUE THREAD

**Issue by dshmaui** [SecKatie/ha-wyzeapi#558]
**Describe the bug**
Every other switch/toggle works, light bulbs represent the correct state/color etc, but the notification toggle doesn't work anymore

**To Reproduce**
I'm not sure how to reproduce this issue since I haven't been able to get the toggle to work since it stopped. 

**System configuration**
System: rpi 4
HA Version: Core 2024.3.1; Supervisor 2024.03.0; Operating System 12.1; Frontend 20240307.0
WyzeApi Version: 0.1.24

**Comment by paulcusick3** [comment]
+1  Only power is available for me

**Comment by brg468** [comment]
@paulcusick3 on what device? The global notification toggle doesn't seem to work right now, but the individual device notification switches are working for me.

**Comment by brg468** [comment]
What kind of cam is WYZE_CAKP2JFUS? And did these work previously?

**Comment by paulcusick3** [comment]
V2 - They worked until about 3 hours ago.

**Comment by brg468** [comment]
The WYZE_CAKP2JFUS is the V3 cam. I have several of those and they all seem to be working. I don't have a V1 to try...

**Comment by paulcusick3** [comment]
right v3 - I'm on 0.1.22
I have WYZEC1-JZ which i think are v2 (eg backdoor)
and WYZE_CAKP2JFUS v3
All of the individual Notification switches are unavail.  The global is avail.  Also Motion is not avail and Siren for V3.

![image](https://github.com/SecKatie/ha-wyzeapi/assets/46980268/252200f2-43d0-470f-9682-00a283bbab67)

**Comment by paulcusick3** [comment]
I just did a full start and see 0.1.24 is avail.  Will try

**Comment by paulcusick3** [comment]
Update fixed.  I've never had to restart to see update pending, but there were a few that showed up after restart

**Comment by brg468** [comment]
Excellent, good to hear!
