### ISSUE TITLE
[Bug] siren can’t be controlled from scene. 

### ISSUE THREAD

**Issue by neilbrookins** [SecKatie/ha-wyzeapi#566]
I’ve created a scene to turn siren on.  This works initially, for the first time only.  But after returning to the scene after initial creation and looking at it again the state of “on” is no longer stored with the scene.  
This means that activating the scene does not turn siren on. 

**To Reproduce**
Create scene. Add device or entity for the siren. Set the state of the siren to on.  Save scene.  Manually turn siren off.  Activate scene and there is no siren heard.  Expected behavior is the siren is heard when scene is activated.  

Home Assistant on a pi4.  
Core
2024.3.1
Supervisor
2024.03.1
Operating System
12.1

WyzeApi Version: latest main release.

**Comment by brg468** [comment]
I believe that is a limitation of all sirens in HomeAssistant, not an issue with this integration. I tried and get this error message. 

`Integration siren does not support reproduce state`
