### ISSUE TITLE
[Wyze notifications ] <The automation that turned on and off the notifications in the Wyze app no longer works.>

### ISSUE THREAD

**Issue by mikefrantz** [SecKatie/ha-wyzeapi#570]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mikefrantz** [comment]
The feature that used to turn on and off the notifications in the Wyze app no longer works in Home Assistant.

**Comment by cmgenius** [comment]
I was having problems with this, but updating to the most recent release via HACS solved the issue for me.

**Comment by brg468** [comment]
Best I can tell it’s still not working.

**Comment by cmgenius** [comment]
What camera(s) are you using? I have only tested using Cam Pan v3 but can confirm notification settings control was working as of yesterday.

**Comment by brg468** [comment]
My individual device notification switches are working, but I think this issue was about the global notification switch that used to toggle all app notifications. That hasn’t been working for a while now, and I’m honestly not sure it’s fixable. But the same can be accomplished more or less with grouping all the device notification switches.

**Comment by mikefrantz** [comment]
I’m using version 2 cameras, and I am also using the latest version of hacs. I use the global switch for turning on and off notifications for all cameras in an automation when I leave the WiFi network. It worked in January and February this year. But sometime after that, it has quit working.

**Comment by mikefrantz** [comment]
I made a notification group and you are correct. It does turn on each individual cameras notification however it will not turn on the push notification to send you an alarm if a person is detected. So it’s the global push notification switch that is not working.

**Comment by brg468** [comment]
As long as the camera is set to notify when a person is detected and you have the global notifications turned on in the app you should get person/vehicle etc notifications if the device motion detection is switched on, at least in iOS. I’ve never personally used the global switch, I just use the device groups.

**Comment by brg468** [comment]
Yea I know, and I know it used to work. But the same can be accomplished by leaving the bell on  and turning device notifications on/off as needed. I haven’t found a way to fix the bell switch, the state isn’t even correct anymore.

**Comment by brg468** [comment]
In guessing when they changed from a straight on/off to all the snooze options they broke the api component.

**Comment by brg468** [comment]
I haven’t looked at all, but maybe if whats suggested here is possible it would be another way of handling it. 

 https://github.com/SecKatie/ha-wyzeapi/issues/581

**Comment by mikefrantz** [comment]
Thank you so much for attempting to fix it. I look forward to the fix. The reason I do it the way I do it is because I have two locations that I monitor.

**Comment by mikefrantz** [comment]
The other problem with doing it as a group and leaving the notifications on the app globally, sensors are not integrated in to Home Assistant and you will always get alarms on your motion sensors, even if you turn the cameras off because it’s set for notifications in the app globally

**Comment by brg468** [comment]
That I didn’t think of, I don’t have any motion sensors. So you’re right that would still be an issue.

**Comment by mikefrantz** [comment]
![IMG_1704](https://github.com/SecKatie/ha-wyzeapi/assets/117596264/c5e6c791-e627-45e5-bcf3-ea6d0e2516c1)
I believe this is what changed that might have broken the global notification. It used to be just on or off. If you could set it to on and until I turn it back on, it would work again like it used to work. Thanks for your continued work on this.

**Comment by mikefrantz** [comment]
I meant to say off and until I turn it back on.

**Comment by brg468** [comment]
Yea I agree that’s probably what changed. For some reason I can’t intercept that specific traffic when I change the notification setting in the app, so I can’t figure out what it’s calling now.

**Comment by chiefspecialk** [comment]
It's weird that in app if you go to Account > Notifications > Push Notifications, it's just a simple toggle and you don't get asked the extra options.  Either doing it that way or with the bell icon and the extra settings accomplish the same thing.

**Comment by mikefrantz** [comment]
Yes, I can toggle the switch in the HA app. But it does not turn on the bell in the Wyze app. So someway is not communicating back-and-forth. I can turn on the bill in the Wyze app and it does not turn on the switch in Home Assistant. Thanks for all your hard work on this.

**Comment by mikefrantz** [comment]
To put it another way the HA app switch has no effect on anything in the Wyze app. Nor does the Wyze app toggle the HA app switch. Hope this helps. Sorry it is such a puzzle to figure out, be we appreciate your work on the app integration.

**Comment by mikefrantz** [comment]
Have you had a chance to investigate why the notification switch does not turn on the bell in the Wyze app?

**Comment by brg468** [comment]
There was some discussion on it here:

https://github.com/SecKatie/ha-wyzeapi/pull/607

**Comment by mikefrantz** [comment]
I was hoping you’d be able to figure this out. But it’s not looking like it’s possible?
