### ISSUE TITLE
[Feature Request] <Please update "Buy Me a Coffee" link>

### ISSUE THREAD

**Issue by Kerdika** [SecKatie/ha-wyzeapi#571]
Your Buy Me a Coffee link goes to a 404 and I would like to support your work! Thank you!

**Comment by minego** [comment]
I second this!

**Comment by stevespaw** [comment]
Same here, I came here looking to see if the thermostat fix build release was here, (not released yet I see) and also to support this effort that I now depend on. Thanks!

**Comment by SecKatie** [comment]
#585 also asked about this but I have fixed it in #588 😃
