### ISSUE TITLE
[Bug] Unknown error happened during updating device info - this is a separate issue

### ISSUE THREAD

**Issue by dinan5** [SecKatie/ha-wyzeapi#575]
**Describe the bug**

**To Reproduce**

1. None, just shows up in log

**Expected behavior**

**System configuration**
System: 
HA Version: 
WyzeApi Version: 

**home-assistant.log**

```
Logger: wyzeapy.services.update_manager
Source: /usr/local/lib/python3.12/site-packages/wyzeapy/services/update_manager.py:46
First occurred: 2:38:37 PM (2 occurrences)
Last logged: 4:40:52 PM

Unknown error happened during updating device info
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/wyzeapy/services/update_manager.py", line 42, in update
    self.device = await self.service.update(self.device)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/wyzeapy/services/switch_service.py", line 25, in update
    device_info = await self._get_property_list(switch)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/wyzeapy/services/base_service.py", line 167, in _get_property_list
    check_for_errors_standard(response_json)
  File "/usr/local/lib/python3.12/site-packages/wyzeapy/utils.py", line 84, in check_for_errors_standard
    raise UnknownApiError(response_json)
wyzeapy.exceptions.UnknownApiError: {'code': '1011', 'msg': 'system limit exceeded, please try again later.', 'traceId': '5a81ec2548de6276504975e5f7946898', 'data': {}}

```

**Comment by glyndon** [comment]
commenting to keep this from going stale. It looks like a rate-limit gets exceeded at random times.

**Comment by dinan5** [comment]
Would it be easier to just say that this API is no longer supported?  Just look at the close reasons for almost all issues - closed as stale. lets just be honest with the community, for all intents and purposes, it is no longer supported.

**Comment by brg468** [comment]
Relax. It’s not unsupported, you’re talking about an issue that is due to a rate limit on the Wyze servers. Other than dramatically reducing polling on everything here there’s not a lot we can do about this specific error. Unless you have a recommendation?

**Comment by dinan5** [comment]
I'm very relaxed. might i suggest you explain the issue(s) in the first place vs letting everything go stale. the stats speak for themselves.

**Comment by brg468** [comment]
It was explained by @glyndon. We’d love more help on resolving issues here if you’re willing to contribute.
