### ISSUE TITLE
[Feature Request] login api change from Wyze

### ISSUE THREAD

**Issue by xcz011** [SecKatie/ha-wyzeapi#576]
I’m an engineer at Wyze, and I wanted to inform you about some important updates to our Wyze Login API that may affect the this project. As detailed in our recent forum post ([Important Wyze App Information - 4/26/24](https://forums.wyze.com/t/important-wyze-app-information-4-26-24/297488)), we will soon be shutting down the v2 and v3 APIs. This decision was made to enhance security and prevent credential stuffing attacks.

We encourage developers to transition to our supported Developer API for login processes which this project already supports. This change will ensure continued compatibility and enhance the security of integrations.

We appreciate the effort you have put into supporting Wyze and our ecosystem through your project. If you have any questions or need further details about the Developer API and how to transition, please feel free to reach out.

Thank you for your understanding and support.

**Comment by brg468** [comment]
@SecKatie, this is a non-issue correct? We’re already using the developer API for login and that’s all this is referring to as far as I can tell.
