### ISSUE TITLE
[Feature Request] Receive Wyze AI detections in Home Assistant

### ISSUE THREAD

**Issue by cmgenius** [SecKatie/ha-wyzeapi#582]
I figure this may be a long shot with the already existing issues surrounding Wyze servers and motion sensor alerts, but nonetheless it would be extremely useful in my installation if Wyze AI detections could be used in Home Assistant. Particularly person detection would be useful, as many basic motion events are triggered by wind, insects, etc.

**Comment by SecKatie** [comment]
This will not be implemented. We can't get this info without overflowing the rate limit 😢
