### ISSUE TITLE
[Bug] unable to update login credentials without removing entire integration

### ISSUE THREAD

**Issue by teddy-ptmedia** [SecKatie/ha-wyzeapi#584]
I need to update the password for the integration to connect again. where can i do this without being forced to remove and re add the entire integration.

**Comment by brg468** [comment]
I don’t think that’s possible, you’ll have to remove and re-add.

**Comment by teddy-ptmedia** [comment]
Is it possible to edit the integration somewhere in a file system? On May 15, 2024, at 6:09 PM, Brian Rogers ***@***.***> wrote:﻿
I don’t think that’s possible, you’ll have to remove and re-add.

**Comment by brg468** [comment]
Possibly in .storage. It’s really not a big deal to re add the integration though.

**Comment by teddy-ptmedia** [comment]
I was looking I. Storage and can’t fine a wayze integrated reference. I have custom entities I’d have to set up again. On May 15, 2024, at 6:30 PM, Brian Rogers ***@***.***> wrote:﻿
Possibly in .storage. It’s really not a big deal to re add the integration though.

**Comment by brg468** [comment]
Try 

/homeassistant/.storage/core.config_entries

**Comment by KAndersonUS** [comment]
> /homeassistant/.storage/core.config_entries

Try setting `data` to an empty object in the config entry for the `wyzeapi` domain in the above file. That should trigger [the config flow](https://developers.home-assistant.io/docs/config_entries_config_flow_handler/) which for this plugin will re-prompt for credentials and API key, which are then [used here](https://github.com/SecKatie/ha-wyzeapi/blob/master/custom_components/wyzeapi/__init__.py#L85).

**Comment by teddy-ptmedia** [comment]
That is easy to do but how do I get the file to be unlocked for editing while HA is running? If I shut down HA I cant access the file to edit it.

**Comment by brg468** [comment]
I just tried it with the file editor addon and it saved with no issues with HA running. I didn’t go through with a restart cause I don’t wanna go through re auth but it seems like it saved just fine. The file shows updated.

**Comment by teddy-ptmedia** [comment]
I did the same thing as you just now but it shows updated and then a moment later all the old data comes right back.

**Comment by SecKatie** [comment]
Is this a bug or a feature request?
