### ISSUE TITLE
Wyze Sense Hub Breaks

### ISSUE THREAD

**Issue by homeassistant348** [SecKatie/ha-wyzeapi#591]
**Describe the bug**
With version 1.25 and 1.26 the Wyze Sense Hub (Alarm Hub) shows as unavailable and no longer is controllable!

**To Reproduce**

After update, Wyze Sense Hub shows as unavailable and is no longer controllable by HA or Apple Home.

**Expected behavior**
Worked fine in version 1.24

**Comment by soundguykin** [comment]
I just updated this morning and noticed the same. I use a lot of automations related to the state of the Sense Hub. Thankfully I was able to roll back to 0.1.24 and it is working again.

**Comment by brg468** [comment]
Any logs? I don’t have sense hub so I probably won’t be much help.

**Comment by homeassistant348** [comment]
Attached is a log file and a couple images for Working/Broken.

￼


Best,
Donald Harriman
***@***.***


Cloud Storage: Get 5GB FREE! <https://shareasale.com/r.cfm?b=732848&u=3661431&m=57377&urllink=&afftrack=>

Backup, sync and share with end-to-end encryption and privacy guaranteed.


WYZE Products 10% Off:

How does a 10% discount off your first Wyze order sound? Use the link below and once you've shopped.
http://rwrd.io/exb5pyh?p

**Comment by homeassistant348** [comment]
[home-assistant_2024-05-23T18-01-27.906Z.log](https://github.com/SecKatie/ha-wyzeapi/files/15420844/home-assistant_2024-05-23T18-01-27.906Z.log)

![Broken](https://github.com/SecKatie/ha-wyzeapi/assets/74278963/67e85327-a790-4e83-bb60-a0b2823c87b5)

![Working](https://github.com/SecKatie/ha-wyzeapi/assets/74278963/32175de3-123a-4590-8bc3-2426551e8431)

**Comment by soundguykin** [comment]
Here are some logs from me as well. My card looks identical to @homeassistant348's.

[home-assistant_wyzeapi_2024-05-23T18-08-18.592Z.log](https://github.com/SecKatie/ha-wyzeapi/files/15420858/home-assistant_wyzeapi_2024-05-23T18-08-18.592Z.log)
[home-assistant_wyzeapi_2024-05-23T18-07-39.955Z.log](https://github.com/SecKatie/ha-wyzeapi/files/15420859/home-assistant_wyzeapi_2024-05-23T18-07-39.955Z.log)

**Comment by spamoni4** [comment]
Same issue, upgraded from 1.24 to 1.26 and now the Sense hub is no longer available.  This is what I see

![image](https://github.com/SecKatie/ha-wyzeapi/assets/81599887/669b01fc-081b-4cdc-ac48-7bf6777aa830)

**Comment by spamoni4** [comment]
@brg468 

I see the "https://github.com/SecKatie/wyzeapy/pull/86" discussion link and based on what I am reading, you don't have the HMS setup to do formal testing.

If you need me to install and test potential fixes, please reach out.  I would be glad to install updates and test the potential fixes, if needed.

**Comment by brg468** [comment]
@spamoni4 thanks for the offer. I don’t have the ability to test the HMS stuff, but since it worked before we changed the auth check, I assume changing back should fix it. If you want to try downloading from  my branch and putting the wyzeapy folder from it in your config folder and restarting, you can test out the updated version. 

https://github.com/brg468/wyzeapy/tree/revert-hms-check

**Comment by spamoni4** [comment]
> @spamoni4 thanks for the offer. I don’t have the ability to test the HMS stuff, but since it worked before we changed the auth check, I assume changing back should fix it. If you want to try downloading from my branch and putting the wyzeapy folder from it in your config folder and restarting, you can test out the updated version.
> 
> https://github.com/brg468/wyzeapy/tree/revert-hms-check

Thanks, will try it this weekend and let you know

**Comment by spamoni4** [comment]
@brg468 

Want to make sure I replace the appropriate items so I have a few Questions, Here is where I think I need to replace (/homeassistant/custom_components/wyzeapi), is this correct?:

![image](https://github.com/SecKatie/ha-wyzeapi/assets/81599887/3da1060f-e577-4e81-a509-326a24e8cada)

I am asking because I don't see a services folder, I would assume that is new and used for references.  

Is there a method which will allow me to access the folder via Windows Explorer or a Mac?

**Comment by spamoni4** [comment]
@brg468 

I just did exactly what you asked and put the wyzapy in the root config folder.  I then went to my dashboard and HMS seems to be working again,

![image](https://github.com/SecKatie/ha-wyzeapi/assets/81599887/76eae1a2-749f-4eab-bb25-c8b492a56f21)

**Comment by brg468** [comment]
Perfect! Sorry I didn’t get to you in time but yes that’s what I meant.

**Comment by spamoni4** [comment]
> Perfect! Sorry I didn’t get to you in time but yes that’s what I meant.

Figured that is what was meant.  So it does seem to fix the issue with HMS.  Great job.  Shall I delete the folder/files you wanted me to test?

One additional question, if you don't mind:  Will you all be adding Leak Sensor Support?  or does this fall into the same issue as with the contact and motion sensors?

**Comment by brg468** [comment]
You can leave the folder there until a new version of Wyze is published, then delete that folder. 

I don’t know anything about how the leak sensor operates, if it’s part of the HMS platform it might be possible but without having one it’s hard to add support.

**Comment by spamoni4** [comment]
> You can leave the folder there until a new version of Wyze is published, then delete that folder.
> 
> I don’t know anything about how the leak sensor operates, if it’s part of the HMS platform it might be possible but without having one it’s hard to add support.

I see, HMS Hub has the Contact, Motion, Leak, and Humidity Sensors as part of it.  If I can provide anything to see about making this happen, let me know.

I also have a spare hub and some sensors. :)

**Comment by brg468** [comment]
This should be fixed in the latest version, 0.1.27

**Comment by spamoni4** [comment]
> This should be fixed in the latest version, 0.1.27

Installing now, will let you know if it corrects the issue.

**Comment by brg468** [comment]
Fixed in https://github.com/SecKatie/wyzeapy/pull/86
