### ISSUE TITLE
[Bug] Regression in 0.1.25 release

### ISSUE THREAD

**Issue by ejpenney** [SecKatie/ha-wyzeapi#594]
**Describe the bug**

Looks like the import for device_registry was removed from sensor.py but it is still used.

**To Reproduce**

1. Update to 0.1.25
2. Restart
3. Integration does not load
4. Check Logs, see error

**Expected behavior**
Integration loads

**System configuration**
System: HASSIO
HA Version: 2024.5.x
WyzeApi Version: 0.1.25

**home-assistant.log**

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:748
integration: Sensor (documentation, issues)
First occurred: 11:41:08 AM (2 occurrences)
Last logged: 11:41:08 AM

Error adding entity None for domain sensor with platform wyzeapi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 748, in _async_add_entity
    if self.config_entry and (device_info := entity.device_info):
                                             ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/sensor.py", line 171, in device_info
    dr.CONNECTION_NETWORK_MAC,
    ^^
NameError: name 'dr' is not defined
```

**Comment by brg468** [comment]
Hmm that shouldn't have happened, I must have missed it when addressing a merge conflict. I'll get a fix out soon.

**Comment by SecKatie** [comment]
This is fixed in the latest release 😃
