### ISSUE TITLE
[Bug] Integration pulls only cameras and Sense Hub not the sensors itself

### ISSUE THREAD

**Issue by Tcsekhar74** [SecKatie/ha-wyzeapi#610]
**Describe the bug**

**To Reproduce**

Install the Integration and configure the service with user name, password, apikey and secret. 

**Expected behavior**

It should pull in all the cameras, contact sensors, motion sensors, temperature sensors, water leak sensors and security panel - but it only pulls the cameras and the sense hub. 

**System configuration**
System: Ubuntu 24
HA Version: 2024.6.4
WyzeApi Version: 0.1.27

**Comment by brg468** [comment]
Please see this comment about why these are no longer supported. 

https://github.com/SecKatie/ha-wyzeapi/issues/320#issuecomment-1001523837
