### ISSUE TITLE
[Feature Request] support 'model_id'

### ISSUE THREAD

**Issue by SecKatie** [SecKatie/ha-wyzeapi#613]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Implement `model_id` as described in the post https://developers.home-assistant.io/blog/2024/07/16/device-info-model-id

**Describe alternatives you've considered**

None considered

**Additional context**

All known info provided

**Comment by brg468** [comment]
Are you thinking just move the current `model` info to `model_id` or try and add an actual model name along with the id? I don't think the API returns anything more than the model number, but I suppose we could put together an enum with the model id/name combos..
