### ISSUE TITLE
[Bug] async_forward_entry_setup without awaiting

### ISSUE THREAD

**Issue by DeathCamel58** [SecKatie/ha-wyzeapi#618]
**Describe the bug**
Warning on start of Home Assistant `2024.8.0` saying that this plugin may stop working on Home Assistant `2025.1`.

**To Reproduce**

1. Start Home Assistant with plugin installed

**Expected behavior**

**System configuration**
System: Bare Metal
HA Version: `2024.8.0`
WyzeApi Version: `0.1.27`

**home-assistant.log**

```
Detected code that calls async_forward_entry_setup for integration, wyzeapi with title: and entry_id: 01J4MV1MV1S1F2Q9BB1EWXWWQ9, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead. Please report this issue.
Detected code that calls async_forward_entry_setup for integration wyzeapi with title: and entry_id: 01J4MV1MV1S1F2Q9BB1EWXWWQ9, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
```

Likely relevant code: https://github.com/SecKatie/ha-wyzeapi/blob/3d46c15e9b70170d4c58d488921bf9f786e86cdf/custom_components/wyzeapi/__init__.py#L123

**Comment by brg468** [comment]
Thanks for the report. Already addressed in https://github.com/SecKatie/ha-wyzeapi/pull/609
