### ISSUE TITLE
Updating to 2024.8.2 loses some entities

### ISSUE THREAD

**Issue by mikefrantz** [SecKatie/ha-wyzeapi#620]
**Describe the bug**
When updating Home Assistant to the latest version, the Wyze camera switches that control. The power and detection are now grayed out.

**To Reproduce**

**Expected behavior**
Home Assistant version 2024.8.1 still worked

**System configuration**

Core
2024.8.1
Supervisor
2024.08.0
Operating System
13.0
Frontend
20240809.0 ⸱ legacy

**home-assistant.log**

```
<PUT YOUR LOG HERE>
```

**Comment by brg468** [comment]
Any errors? I just upgraded from 2024.8.0 to 8.2 and everything came up fine..

You might have to delete and re-add the integration if it’s still giving you issues.

**Comment by brg468** [comment]
Since there wasn’t a reply and no other reports I’m gonna go ahead and close.
