### ISSUE TITLE
Wyzeapi warnings when Home Assistant starts up

### ISSUE THREAD

**Issue by jeprice77** [SecKatie/ha-wyzeapi#623]
When Home Assistant starts up I get the following 2 warnings.  Everything works fine but it appears later versions of Home Assistant Core will be a problem.  Perhaps someone has already reported these warnings.

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:151
First occurred: 12:40:23 PM (14 occurrences)
Last logged: 12:40:28 PM

Detected code that calls async_forward_entry_setup for integration, wyzeapi with title: and entry_id: a3d330aa92a2d3e6c8f9113eb0b71356, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead. Please report this issue.

Detected code that calls async_forward_entry_setup for integration wyzeapi with title: and entry_id: a3d330aa92a2d3e6c8f9113eb0b71356, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by SecKatie** [comment]
@brg468 do you have cycles to work this? If not I can try to make some time here next week.

**Comment by brg468** [comment]
Already fixed in https://github.com/SecKatie/ha-wyzeapi/pull/609 😁
