### ISSUE TITLE
[Bug] Outdoor Plug not responding

### ISSUE THREAD

**Issue by Likaybai** [SecKatie/ha-wyzeapi#624]
Indoor plugs and light bulbs work except all my outdoor plugs. This happened after updated to latest core.

**Comment by brg468** [comment]
Did you try deleting and re-setting up the integration? That’s about all I could suggest, nothing should have changed that affects those plugs.

**Comment by Likaybai** [comment]
Suddenly it's working now. I don't how. Thanks.
