### ISSUE TITLE
Wyze Camera Floodlight Switch

### ISSUE THREAD

**Issue by jeprice77** [SecKatie/ha-wyzeapi#628]
I have been using the Wyze integration for a while now to control three Wyze V3 cameras.  I always noticed that under the device controls there was a switch entity for floodlight.  Since the V3 does not have a light I never really gave it much thought.  Today I purchased a new Wyze V4 which has a floodlight built-in to the camera.  When I added the device to Home Assistant, there was no switch entity to control the light.  It seems odd that the V3 cameras have the switch control but the V4 switch is missing.  Wondering if this is a bug or if the V4 is not fully supported.

**Comment by KyGuy2002** [comment]
IIRC the v3 floodlight switch should still be present and working.  The newer all in one "Floodlight v2" does not work as it uses the IOTC protocol.  The Floodlight Pro should work.

**Comment by kylegrymonprez** [comment]
Is there any way then to be able to control the floodlight v2 from turning on in HA?

**Comment by KyGuy2002** [comment]
If you use Wyze Docker Bridge with its HA integration I think you might be able to.  They use IOTC because they maintain a connection to the cameras stream.

**Comment by brg468** [comment]
I think this is fixed to the extent it can be. For now the V2 floodlight and the V4 cam built-in light are not controllable. The V3 cam optional light now shows if attached. Thanks @KyGuy2002
