### ISSUE TITLE
[Bug] Can't login via Google OAuth

### ISSUE THREAD

**Issue by adarsh** [SecKatie/ha-wyzeapi#631]
**Describe the bug**
On the screen where we submit the API key and Key ID, there is no option for me to login via OAurh, which is how I created my account with Wyze

**To Reproduce**

1. Go to API portal
2. Notice a lack of OAuth options

**Expected behavior**
An OAuth Google button

**Comment by Paulie420** [comment]
same here - I used my google account to setup my Wyze devices. 

I was able to create an API key on the Wyze site, but can't login via Google OAuth - if I need to make a new Wyze account using Wyze only I will, but posting here to ask.

**Comment by brg468** [comment]
I just tried making an account with Google Oauth and using those credentials to create the API keys in the dev portal. I used my google email/password and those keys in HA and it seemed to work fine. Is that not working for you?

**Comment by adarsh** [comment]
> I just tried making an account with Google Oauth and using those credentials to create the API keys in the dev portal. I used my google email/password and those keys in HA and it seemed to work fine. Is that not working for you?

Aha! I wouldn't have thought to use my _Google_ user and password. Perhaps addition of a hint text on that page for OAuth users would be helpful?

**Comment by brg468** [comment]
👍 I will look into adding something to make that more clear.

**Comment by brg468** [comment]
@adarsh does something like this make it a little more clear if we add to the login page? It would show up below the username and password fields.

```
 "username": "Wyze or 3rd party OAuth email address",
 "password": "Wyze or 3rd party OAuth password"
```
