### ISSUE TITLE
[Bug] Notifications Toggle not working for OG Cams

### ISSUE THREAD

**Issue by jmzahra19** [SecKatie/ha-wyzeapi#639]
The Notifications On/Off toggle within the Home Assistant integration has no effect on the Notifications toggle within the Wyze app for all of my OG Cams.

The toggle _does_ work for my Floodlight Cams.

**Model:** Wyze Cam OG
**Firmware Version:** 1.0.84 (latest)
**Wyze App Version:** 3.1.5 (569)

I can provide more details if needed. I just updated the firmware for these cams yesterday, and just started testing this integration today, so I can't say whether the new firmware broke this functionality or if it never worked.

**Comment by brg468** [comment]
You can try downloading the beta release through HACS. I think it should be fixed in that version.

**Comment by jmzahra19** [comment]
Working in the beta... thank you!

Are there any plans to get the universal notifications toggle working? I have a Sense Hub and cannot control notifications from sensors using this integration (I'm getting rid of IFTTT in favor of HA, but this will be the one missing component).

**Comment by brg468** [comment]
So far we haven’t found a solution to fixing it. So at the moment no but hopefully someday.
