### ISSUE TITLE
[Bug] Deptacted code

### ISSUE THREAD

**Issue by M-Dot613** [SecKatie/ha-wyzeapi#640]
**Describe the bug**
The error logs show a deprecated usage of `async_forward_entry_setup` in the WyzeAPI integration. The error indicates that the code does not await `async_forward_entry_setup`, which will cause issues in Home Assistant versions 2025.1 and beyond. The warning also suggests that this code needs to be updated to avoid future issues when Home Assistant 2025.6 is released.

**To Reproduce**
1. Install the WyzeAPI integration in Home Assistant.
2. Start Home Assistant.
3. Check the logs after a restart.
4. See the warning about `async_forward_entry_setup` not being awaited.

**Expected behavior**
The code should use `await async_forward_entry_setup` instead of `async_forward_entry_setup` to avoid deprecated behavior and prevent issues in future versions of Home Assistant.

**System configuration**
System: Docker
HA Version: 2024.8.3
WyzeApi Version: 0.1.27

**home-assistant.log**
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:151
First occurred: 1:50:06 AM (9 occurrences)
Last logged: 1:50:07 AM

Detected code that calls async_forward_entry_setup for integration, wyzeapi with title: and entry_id: ***, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead. Please report this issue.
Detected code that calls async_forward_entry_setup for integration wyzeapi with title: and entry_id: ***, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
```

**Comment by M-Dot613** [comment]
for now i just rolled back a version

**Comment by brg468** [comment]
It’s been fixed and is in the available beta version. Just waiting for the owner to push out a new stable version.
