### ISSUE TITLE
[Bug] Wyze outdoor plug almost works

### ISSUE THREAD

**Issue by minorOffense** [SecKatie/ha-wyzeapi#642]
**Describe the bug**
The Wyze integration sees the outdoor plug but only lists it as a single switch. So when you try to read data or toggle the switch nothing happens. 

**To Reproduce**

1. Go to add devices from Wyze
2. Click on outdoor switch
3. Toggle the switch
4. The switch state doesn’t change (confirmed IRL at the switch and in the Wyze App)
5. Also there’s only a single entity listed. Should be two for each plug on the device. 

https://www.wyze.com/products/wyze-plug-outdoor

**Expected behavior**
Outdoor switch should appear as two switches and change state correctly. 

**System configuration**
System: OVA
HA Version: 2024.11.3
WyzeApi Version: Latest? Not sure how to tell

**home-assistant.log**
There’s no errors logged from what I could tell. Just seems sort of half working.  But I’ll see if other actions cause some logs to appear.

**Comment by brg468** [comment]
There should be 3 devices added. One for the plug that reports combined energy (but with a switch that doesn’t seem to function), and then 2 more devices for each outlet.

**Comment by minorOffense** [comment]
You are correct! Sorry I added it and kept searching for "Wyze" or "Outdoor" in the entities. Never thought to look for the name I gave the plugs individually.

Sorry to bother you.

**Comment by brg468** [comment]
No problem! In the future I may try to see if it’s possible to combine into one device, which would make more sense.
