### ISSUE TITLE
Latest Version Won't Start

### ISSUE THREAD

**Issue by bjs-pdx** [SecKatie/ha-wyzeapi#653]
**Describe the bug**

Installed the latest version of the integration and now it won't start.  Get this error:

Logger: homeassistant.setup
Source: setup.py:271
First occurred: 8:32:35 PM (1 occurrences)
Last logged: 8:32:35 PM

Setup failed for custom integration 'wyzeapi': Requirements for wyzeapi not found: ['wyzeapy>=0.5.26,<0.6'].

**To Reproduce**

**Expected behavior**

**System configuration**
System: 
HA Version: 
WyzeApi Version: 

**home-assistant.log**

```
<PUT YOUR LOG HERE>
```
![image](https://github.com/user-attachments/assets/5310819e-ad5c-489c-b31c-8331d4d0c3c7)

**Comment by andrew-davis** [comment]
I just updated and have the same issue. They Wyze integration errors on start.

What can I provide to help troubleshoot? Is there a way to roll back to the previous version? Thank you to the team that works on this!!!

![image](https://github.com/user-attachments/assets/2f94ac40-e994-4722-835e-319a2393452f)
![image](https://github.com/user-attachments/assets/458cc34c-cb31-4721-abbe-b86c0c4ed54f)

**Comment by brg468** [comment]
https://github.com/SecKatie/ha-wyzeapi/blob/9b206784e6d36864a43011af5649ed2d58b2d5a8/custom_components/wyzeapi/alarm_control_panel.py#L10-L11

@SecKatie I think this needs to be imported from `homeassistant.components.alarm_control_panel.const`
I’m not in front of a PC so I can’t test anything right now but that should fix it.

**Comment by brg468** [comment]
> Is there a way to roll back to the previous version?

You can roll back by going to HACS -> redownload and pick the last version.

**Comment by andrew-davis** [comment]
> > Is there a way to roll back to the previous version?
> 
> You can roll back by going to HACS -> redownload and pick the last version.

Oh, wow. That was easy! I rolled back to 0.1.28, restarted, and the integration started and is working as expected with all devices recognized and connected again. Cheers!

**Comment by bjs-pdx** [comment]
Tried to rollback to 0.1.28 but my install won't start.

[home-assistant_2024-12-11T16-47-57.388Z.log](https://github.com/user-attachments/files/18099391/home-assistant_2024-12-11T16-47-57.388Z.log)

**Comment by brg468** [comment]
@andrew-davis what HA version are you on?

**Comment by bjs-pdx** [comment]
![image](https://github.com/user-attachments/assets/db2dd835-95a3-4b83-bd31-a877a2e43461)

**Comment by brg468** [comment]
@bjs-pdx that’s probably the reason for the dependency conflict. You’re on an HA version from July. I would recommend updating that and see if it works.

**Comment by bjs-pdx** [comment]
I'm using docker version...I don't seem to find any updates.  Also, how do I trigger a screen to allow me to re-enter my api keys?  Can't seem to get there and I think that could be the problem.

**Comment by brg468** [comment]
I’m not sure the process for updating docker, but have a look here: https://www.home-assistant.io/installation/linux#install-home-assistant-container

There isn’t a way to bring up the credentials screen again without deleting and reinstalling the Wyze integration, but based on the errors you provided it looks to be a dependency issue not a credential issue.

**Comment by bjs-pdx** [comment]
I would think if it was a dependency rolling back to 0.1.28 would have fixed it.  It didn't.  Still won't start.

**Comment by brg468** [comment]
You sure you were on 0.1.28 before?

**Comment by bjs-pdx** [comment]
Not positive but 0.1.29 was the only update so I assume it was 0.1.28.

**Comment by brg468** [comment]
Try 0.1.27.

That has an older dep version

**Comment by bjs-pdx** [comment]
I need to review how-to on upgrading docker version of HA.
