### ISSUE TITLE
Devices don't show up in Automations

### ISSUE THREAD

**Issue by JustCallMeCrash** [SecKatie/ha-wyzeapi#73]
Trying to automate some of my Wyze devices, but they don't show up in the list when I try to automate them.  I have 8 Wyze bulbs and 4 Wyze plugs, they all show up on Lovelace, but aren't available for automations.

**Comment by JoshuaMulliken** [comment]
They are called entities. To use them in automations you have to call the light service and target the entity with the light.on

![Adding Entity to Automation](https://i.imgur.com/BCwqhMp.png)

**Comment by JustCallMeCrash** [comment]
Oh, man!  Thank you - I had been beating my head against this.

**Comment by JoshuaMulliken** [comment]
@JustCallMeCrash no worries!

**Comment by oliverkurth** [comment]
Can we have this documented? It took me some time figure this out. It's counterintuitive, because this is very different to the kasa switches/plugs which I had already working. I was assuming it would be the same.

Actually I created a workaround by editing the yaml like this (copied from the kasa switches and using a random id):
```
-  type: turn_on
    device_id: 2c9119983fa5b04fb090722fa7c4ebf5
    entity_id: switch.kitchen_window_lights
    domain: switch
```
I was going to file a bug, but found this issue when searching for it.

**Comment by oudoulj** [comment]
> Can we have this documented? It took me some time figure this out. It's counterintuitive, because this is very different to the kasa switches/plugs which I had already working. I was assuming it would be the same.
> 
> ...
> I was going to file a bug, but found this issue when searching for it.

Yep, same as above.
I scratched my head a while desperately looking for a bulb device to add to my automation before I dug up that thread.
I think it would be worth adding this "Call service" example to the readme :wink: 
Thank you again for the handy integration !

**Comment by JoshuaMulliken** [comment]
@oliverkurth @oudoulj I will type something up in the readme!

**Comment by JoshuaMulliken** [comment]
I have added a section to the readme in this commit: https://github.com/JoshuaMulliken/ha-wyzeapi/commit/db71d27baab72d622fd97701fb4482f98624cdba
